/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.qlNhanVien;

import controller.NhanVienDAO;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import view.main.Main;

/**
 *
 * @author hung
 */
public class QLNhanVien extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<NhanVien> nvList;

    /**
     * Creates new form ListKhachHang
     */
    public QLNhanVien() throws ClassNotFoundException, IOException, FileNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tblNhanVien.getModel();
        showNhanVien();
    }

    public void showNhanVien() throws ClassNotFoundException, IOException, FileNotFoundException, SQLException {
        nvList = NhanVienDAO.getAllNhanVien();
        tableModel.setRowCount(0);
        nvList.forEach(nv -> {
            tableModel.addRow(new Object[]{
                nv.getMa_nv(), nv.getHoTen(),
                new SimpleDateFormat("dd/MM/yyyy").format(nv.getNgay_sinh()),
                nv.getSdtString(), nv.getEmail(), nv.getLuong()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        themBTN = new javax.swing.JButton();
        suaBTN = new javax.swing.JButton();
        xoaBTN = new javax.swing.JButton();
        lamMoiBTN = new javax.swing.JButton();
        troVeBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản lý nhân viên");

        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ tên", "Ngày sinh", "SĐT", "Email", "Lương"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNhanVien.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        themBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        themBTN.setText("Thêm");
        themBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBTNActionPerformed(evt);
            }
        });

        suaBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        suaBTN.setText("Sửa");
        suaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBTNActionPerformed(evt);
            }
        });

        xoaBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        xoaBTN.setText("Xoá");
        xoaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBTNActionPerformed(evt);
            }
        });

        lamMoiBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lamMoiBTN.setText("Làm mới");
        lamMoiBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamMoiBTNActionPerformed(evt);
            }
        });

        troVeBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        troVeBTN.setText("Trở về");
        troVeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troVeBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xoaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(troVeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lamMoiBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBTN)
                    .addComponent(suaBTN)
                    .addComponent(xoaBTN)
                    .addComponent(lamMoiBTN)
                    .addComponent(troVeBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void troVeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troVeBTNActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_troVeBTNActionPerformed

    private void themBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBTNActionPerformed
        // TODO add your handling code here:
        new ThemNhanVien(this, true).setVisible(true);
    }//GEN-LAST:event_themBTNActionPerformed

    private void suaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBTNActionPerformed
        // TODO add your handling code here:
        int row = tblNhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn nhân viên muốn sửa", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                int ma_nv = (int) tblNhanVien.getValueAt(row, 0);
                new SuaNhanVien(this, true, ma_nv).setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(
                        this, "<html><body><p style='width: 200px;'>" + ex.getMessage() + "</p></body></html>",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_suaBTNActionPerformed

    private void xoaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBTNActionPerformed
        // TODO add your handling code here:
        int row = tblNhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn nhân viên muốn xoá", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        } else {
            if (JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                try {
                    int ma_nv = (int) tblNhanVien.getValueAt(row, 0);
                    NhanVienDAO.deleteNhanVien(ma_nv);
                    JOptionPane.showMessageDialog(this, "Xoá thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    showNhanVien();
                } catch (ClassNotFoundException | IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(
                            this, "<html><body><p style='width: 200px;'>" + ex.getMessage() + "</p></body></html>",
                            "Lỗi", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_xoaBTNActionPerformed

    private void lamMoiBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamMoiBTNActionPerformed
        try {
            // TODO add your handling code here:
            showNhanVien();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    this, "<html><body><p style='width: 200px;'>" + ex.getMessage() + "</p></body></html>",
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lamMoiBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLNhanVien().setVisible(true);
                } catch (ClassNotFoundException | IOException | SQLException ex) {
                    Logger.getLogger(QLNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lamMoiBTN;
    private javax.swing.JButton suaBTN;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JButton themBTN;
    private javax.swing.JButton troVeBTN;
    private javax.swing.JButton xoaBTN;
    // End of variables declaration//GEN-END:variables
}
