/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.qlKhachHang;

import java.util.*;
import java.io.*;
import java.sql.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import controller.KhachHangDAO;
import model.KhachHang;
import javax.swing.JOptionPane;

/**
 *
 * @author hung
 */
public class SuaKhachHang extends javax.swing.JDialog {

    QLKhachHang father;
    private int ma_kh;

    /**
     * Creates new form SuaKH
     */
    public SuaKhachHang(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setResizable(false);
    }

    public SuaKhachHang(javax.swing.JFrame parent, boolean modal, int ma_kh)
            throws ClassNotFoundException, IOException, FileNotFoundException, SQLException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.ma_kh = ma_kh;
        this.father = (QLKhachHang) parent;
        KhachHang kh = KhachHangDAO.getKhachHang(ma_kh);
        txtHo.setText(kh.getHo());
        txtTenDem.setText(kh.getTen_dem());
        txtTen.setText(kh.getTen());
        txtSdt.setText(kh.getSdtString());
        txtSoNha.setText(kh.getSo_nha());
        txtDuong.setText(kh.getDuong());
        txtQuanHuyen.setText(kh.getQuan_huyen());
        txtTinhTp.setText(kh.getTinh_tp());
    }

    private boolean checkEmpty() {
        if (txtHo.getText().isBlank() || txtTen.getText().isBlank() || txtSdt.getText().isBlank()
                || txtQuanHuyen.getText().isBlank() || txtTinhTp.getText().isBlank()) {
            return true;
        }
        return false;
    }

    private boolean checkValid() {
        String[] w = txtSdt.getText().replace("\\s+", "").split(",");
        for (String sdt : w) {
            if (!sdt.trim().matches("^(0)(3|5|7|8|9)([0-9]{8})$")) {
                JOptionPane.showMessageDialog(this, "Nhập số điện thoại có 10 chữ số,\n bắt đầu bằng 03, 05, 07, 08, 09",
                        "Lỗi định dạng", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        String s = txtHo.getText() + txtTenDem.getText() + txtTen.getText();
        if (!s.matches("^([a-zA-Zàáãạảăắằẳẵặâấầẩẫậèéẹẻẽêềếểễệđìíĩỉịòóõọỏôốồổỗộơớờởỡợùúũụủưứừửữựỳỵỷỹý"
                + "ÀÁÃẠẢĂẮẰẲẴẶÂẤẦẨẪẬÈÉẸẺẼÊỀẾỂỄỆĐÌÍĨỈỊÒÓÕỌỎÔỐỒỔỖỘƠỚỜỞỠỢÙÚŨỤỦƯỨỪỬỮỰỲỴỶỸÝ\\s\\/]+)$")) {
            JOptionPane.showMessageDialog(rootPane, "Kiểm tra lại định dạng họ tên",
                    "Lỗi định dạng", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblTenDem = new javax.swing.JLabel();
        txtTenDem = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblSdt = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        lblSoNha = new javax.swing.JLabel();
        txtSoNha = new javax.swing.JTextField();
        lblDuong = new javax.swing.JLabel();
        txtDuong = new javax.swing.JTextField();
        lblQuanHuyen = new javax.swing.JLabel();
        txtQuanHuyen = new javax.swing.JTextField();
        lblTinhTP = new javax.swing.JLabel();
        txtTinhTp = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa thông tin khách hàng");

        lblHo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblHo.setText("Họ*");

        txtHo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTenDem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenDem.setText("Tên đệm");

        txtTenDem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTen.setText("Tên*");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblSdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSdt.setText("SĐT*");

        txtSdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblSoNha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSoNha.setText("Số nhà");

        txtSoNha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDuong.setText("Đường");

        txtDuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblQuanHuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuanHuyen.setText("Quận/Huyện*");

        txtQuanHuyen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTinhTP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTinhTP.setText("Tỉnh/Thành phố*");

        txtTinhTp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQuanHuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSoNha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTinhTP, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addComponent(lblSdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTenDem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtQuanHuyen, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDuong, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSoNha, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTinhTp, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHo)
                                .addComponent(txtTenDem)
                                .addComponent(txtTen)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHo)
                    .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDem)
                    .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTen)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSdt)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoNha)
                    .addComponent(txtSoNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuong)
                    .addComponent(txtDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuanHuyen)
                    .addComponent(txtQuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTinhTP)
                    .addComponent(txtTinhTp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (checkEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đủ thông tin", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            if (checkValid()) {
                try {
                    // TODO add your handling code here:
                    ArrayList<String> sdtList = new ArrayList<>(
                            Arrays.asList(txtSdt.getText().replaceAll("\\s+", "").split(",")));
                    Set<String> set = new LinkedHashSet<>();
                    set.addAll(sdtList);
                    sdtList.clear();
                    sdtList.addAll(set);
                    KhachHang kh = new KhachHang(ma_kh, txtHo.getText().trim(), txtTenDem.getText().trim(),
                            txtTen.getText().trim(), txtDuong.getText().isBlank() ? "" : txtSoNha.getText().trim(),
                            txtDuong.getText().trim(), txtQuanHuyen.getText().trim(),
                            txtTinhTp.getText().trim(), sdtList);
                    KhachHangDAO.updateKhachHang(kh);
                    JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                    father.showKhachHang();
                    this.dispose();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SuaKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SuaKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(
                            this, "<html><body><p style='width: 200px;'>" + ex.getMessage() + "</p></body></html>",
                            "Lỗi", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(SuaKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaKhachHang dialog = new SuaKhachHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel lblDuong;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblQuanHuyen;
    private javax.swing.JLabel lblSdt;
    private javax.swing.JLabel lblSoNha;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenDem;
    private javax.swing.JLabel lblTinhTP;
    private javax.swing.JTextField txtDuong;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtQuanHuyen;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoNha;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    private javax.swing.JTextField txtTinhTp;
    // End of variables declaration//GEN-END:variables
}
